# Generated by Django 4.0.4 on 2022-05-16 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField(default=0.0)),
                ('product_discount', models.FloatField(blank=True, null=True)),
                ('product_quantity_type', models.CharField(choices=[('250GM', '250 grams'), ('500GM', '500 grams'), ('750GM', '750 grams'), ('1000GM', '1 kg'), ('1PC', '1 Pc'), ('12PC', '12 Pc')], max_length=6)),
                ('product_type', models.CharField(choices=[('V', 'Vegetable'), ('F', 'Fruit')], max_length=1)),
                ('product_description', models.TextField(blank=True, max_length=500, null=True)),
                ('product_quantity', models.IntegerField()),
                ('product_photo', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_created', models.DateTimeField(auto_now_add=True)),
                ('wishlist_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('wishlist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
